version: '3.8'

services:
  nginx:
    image: ${CONTAINER_REGISTRY_BASE}/nginx:latest
    environment:
      FPM_ENTRYPOINT: index
      PHP_FPM_CONTAINER: php-fpm
      NGINX_PROJECT: prod-demo
      NGINX_HOST: lunamy.com
      NGINX_ROOT_DIR: public
    depends_on:
      - php-fpm
    ports:
      - "8110:80"
      - "8111:443"

  php-fpm:
    image: ${CONTAINER_REGISTRY_BASE}/php-fpm:latest